# language: fr
Fonctionnalité: Gestion du paquet de cartes

  Scénario: Initialisation d'un paquet de cartes neuves
    Et que le jeu de carte simple est neuf
    Quand je récupère le paquet de cartes
    Alors il doit être trié par couleur et ordre croissant
      | color  | value |
      | BLUE   | ZERO  |
      | BLUE   | ONE   |
      | BLUE   | ONE   |
      | BLUE   | TWO   |
      | BLUE   | TWO   |
      | BLUE   | THREE |
      | BLUE   | THREE |
      | BLUE   | FOUR  |
      | BLUE   | FOUR  |
      | BLUE   | FIVE  |
      | BLUE   | FIVE  |
      | BLUE   | SIX   |
      | BLUE   | SIX   |
      | BLUE   | SEVEN |
      | BLUE   | SEVEN |
      | BLUE   | EIGHT |
      | BLUE   | EIGHT |
      | BLUE   | NINE  |
      | BLUE   | NINE  |
      | RED    | ZERO  |
      | RED    | ONE   |
      | RED    | ONE   |
      | RED    | TWO   |
      | RED    | TWO   |
      | RED    | THREE |
      | RED    | THREE |
      | RED    | FOUR  |
      | RED    | FOUR  |
      | RED    | FIVE  |
      | RED    | FIVE  |
      | RED    | SIX   |
      | RED    | SIX   |
      | RED    | SEVEN |
      | RED    | SEVEN |
      | RED    | EIGHT |
      | RED    | EIGHT |
      | RED    | NINE  |
      | RED    | NINE  |
      | YELLOW | ZERO  |
      | YELLOW | ONE   |
      | YELLOW | ONE   |
      | YELLOW | TWO   |
      | YELLOW | TWO   |
      | YELLOW | THREE |
      | YELLOW | FOUR  |
      | YELLOW | FOUR  |
      | YELLOW | FOUR  |
      | YELLOW | FIVE  |
      | YELLOW | FIVE  |
      | YELLOW | SIX   |
      | YELLOW | SIX   |
      | YELLOW | SEVEN |
      | YELLOW | SEVEN |
      | YELLOW | EIGHT |
      | YELLOW | EIGHT |
      | YELLOW | NINE  |
      | YELLOW | NINE  |
      | GREEN  | ZERO  |
      | GREEN  | ONE   |
      | GREEN  | ONE   |
      | GREEN  | TWO   |
      | GREEN  | TWO   |
      | GREEN  | THREE |
      | GREEN  | THREE |
      | GREEN  | FOUR  |
      | GREEN  | FOUR  |
      | GREEN  | FIVE  |
      | GREEN  | FIVE  |
      | GREEN  | SIX   |
      | GREEN  | SIX   |
      | GREEN  | SEVEN |
      | GREEN  | SEVEN |
      | GREEN  | EIGHT |
      | GREEN  | EIGHT |
      | GREEN  | NINE  |
      | GREEN  | NINE  |
